#ifndef IDEVICELOADERS_H
#define IDEVICELOADERS_H

#include <stdlib.h>

typedef struct device_loader {
	char* identifier;
    char* ibss_ivkey;
	char* ibss_path;
    char* ibec_ivkey;
	char* ibec_path;
	char* devicetree_path;
    char* trustcache_path;
	char* kernelcache_path;
    char* ramdisk_path;
    char* ipsw_url;
} device_loader;

static const device_loader device_loaders[] = {
	{ "iPhone1,1",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone1,2",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone2,1",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone3,1",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone3,2",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone3,3",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone4,1",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    { "iPhone5,1",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    { "iPhone5,2",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    { "iPhone5,3",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    { "iPhone5,4",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone6,1",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone6,2",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone7,1",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone7,2",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone8,1",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone8,1",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone8,2",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone8,2",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone8,4",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone8,4",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone9,1",   "", "Firmware/dfu/iBSS.d10.RELEASE.im4p", "", "Firmware/dfu/iBEC.d10.RELEASE.im4p", "Firmware/all_flash/DeviceTree.d10ap.im4p", "Firmware/018-61747-017.dmg.trustcache", "kernelcache.release.iphone9", "018-61747-017.dmg", "https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98010/39CE5096-991E-4C25-87BF-7FF9181C07CA/iPhone_4.7_P3_14.8_18H17_Restore.ipsw"},
	{ "iPhone9,2",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    { "iPhone9,3",   "", "Firmware/dfu/iBSS.d10.RELEASE.im4p", "", "Firmware/dfu/iBEC.d10.RELEASE.im4p", "Firmware/all_flash/DeviceTree.d10ap.im4p", "Firmware/018-61747-017.dmg.trustcache", "kernelcache.release.iphone9", "018-61747-017.dmg", "https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98010/39CE5096-991E-4C25-87BF-7FF9181C07CA/iPhone_4.7_P3_14.8_18H17_Restore.ipsw"},
	{ "iPhone9,4",   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    { "iPhone10,1", "", "Firmware/dfu/iBSS.d10.RELEASE.im4p", "", "Firmware/dfu/iBEC.d10.RELEASE.im4p", "Firmware/all_flash/DeviceTree.d10ap.im4p", "Firmware/018-61747-017.dmg.trustcache", "kernelcache.release.iphone9", "018-61747-017.dmg", "https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98010/39CE5096-991E-4C25-87BF-7FF9181C07CA/iPhone_4.7_P3_14.8_18H17_Restore.ipsw"},
	{ "iPhone10,2",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone10,3",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    { "iPhone10,4",  "", "Firmware/dfu/iBSS.d10.RELEASE.im4p", "", "Firmware/dfu/iBEC.d10.RELEASE.im4p", "Firmware/all_flash/DeviceTree.d10ap.im4p", "Firmware/018-61747-017.dmg.trustcache", "kernelcache.release.iphone9", "018-61747-017.dmg", "https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98010/39CE5096-991E-4C25-87BF-7FF9181C07CA/iPhone_4.7_P3_14.8_18H17_Restore.ipsw"},
	{ "iPhone10,5",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone10,6",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone11,2",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone11,4",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone11,6",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone11,8",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone12,1",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone12,3",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPhone12,5",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPod1,1",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPod2,1",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPod3,1",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPod4,1",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPod5,1",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPod7,1",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPod9,1",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad1,1",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad2,1",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad2,2",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad2,3",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad2,4",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad2,5",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad2,6",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad2,7",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad3,1",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad3,2",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad3,3",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    { "iPad3,4",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad3,5",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad3,6",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad4,1",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad4,2",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad4,4",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad4,5",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad4,6",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad4,7",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad4,8",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad4,9",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad5,1",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad5,2",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad5,3",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad5,4",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad6,3",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad6,4",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad6,7",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad6,8",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad6,11",    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad6,11",    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad6,12",    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad6,12",    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad7,1",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad7,2",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad7,3",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad7,4",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad7,5",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad7,6",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad7,11",    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad7,12",    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad8,1",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad8,2",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad8,3",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad8,4",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad8,5",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad8,6",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad8,7",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad8,8",     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad11,1",    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad11,2",    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad11,3",    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "iPad11,4",    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "AppleTV2,1",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "AppleTV3,1",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "AppleTV3,2",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "AppleTV5,3",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ "AppleTV6,2",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
	{ NULL,          NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
};

#endif
